# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XaGv4zD4svKRDSCmI41LLqjACzB0mzhM
"""

!pip install -q streamlit pyngrok

import re
import json
import time
import joblib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

from google.colab import files

print("Upload twitter_training.csv")
files.upload()

print("Upload twitter_validation.csv")
files.upload()

import os
os.makedirs("data", exist_ok=True)
os.rename("twitter_training.csv", "data/twitter_training.csv")
os.rename("twitter_validation.csv", "data/twitter_validation.csv")

COLUMN_NAMES = ["id", "entity", "sentiment", "text"]

def clean_text(text: str) -> str:
    text = str(text).lower()
    text = re.sub(r"http\S+|www\.\S+", " ", text)      # URLs
    text = re.sub(r"@\w+", " ", text)                   # mentions
    text = re.sub(r"[^a-z\s]", " ", text)                # keep letters only
    text = re.sub(r"\s+", " ", text).strip()             # extra whitespace
    return text

def prepare_dataset(train_path, val_path):
    train_df = pd.read_csv(train_path, header=None, names=COLUMN_NAMES)
    val_df = pd.read_csv(val_path, header=None, names=COLUMN_NAMES)

    for df in (train_df, val_df):
        df.dropna(subset=["text"], inplace=True)
        df["clean_text"] = df["text"].apply(clean_text)
        df.drop_duplicates(subset=["clean_text"], inplace=True)
        df.query("clean_text != ''", inplace=True)
        df.reset_index(drop=True, inplace=True)

    return train_df, val_df

train_df, val_df = prepare_dataset("data/twitter_training.csv", "data/twitter_validation.csv")
print("Training rows:", len(train_df))
print("Validation rows:", len(val_df))
train_df.head()

os.makedirs("models", exist_ok=True)

label_encoder = LabelEncoder()
y_train = label_encoder.fit_transform(train_df["sentiment"])
y_val = label_encoder.transform(val_df["sentiment"])

vectorizer = TfidfVectorizer(max_features=20000, ngram_range=(1, 2))
X_train_tfidf = vectorizer.fit_transform(train_df["clean_text"])
X_val_tfidf = vectorizer.transform(val_df["clean_text"])

nb_model = MultinomialNB()
nb_model.fit(X_train_tfidf, y_train)

nb_pred = nb_model.predict(X_val_tfidf)
nb_accuracy = accuracy_score(y_val, nb_pred)

print(f"Multinomial Naive Bayes validation accuracy: {nb_accuracy:.4f}")
print(classification_report(y_val, nb_pred, target_names=label_encoder.classes_))

joblib.dump(nb_model, "models/naive_bayes_model.joblib")
joblib.dump(vectorizer, "models/tfidf_vectorizer.joblib")
joblib.dump(label_encoder, "models/label_encoder.joblib")

with open("models/nb_accuracy.json", "w") as f:
    json.dump({"model": "Multinomial NB", "accuracy": nb_accuracy}, f)

VOCAB_SIZE = 20000
MAX_LEN = 40
EMBED_DIM = 128
RNN_UNITS = 128

tokenizer = Tokenizer(num_words=VOCAB_SIZE, oov_token="<OOV>")
tokenizer.fit_on_texts(train_df["clean_text"])

X_train_seq = pad_sequences(
    tokenizer.texts_to_sequences(train_df["clean_text"]),
    maxlen=MAX_LEN, padding="post", truncating="post",
)
X_val_seq = pad_sequences(
    tokenizer.texts_to_sequences(val_df["clean_text"]),
    maxlen=MAX_LEN, padding="post", truncating="post",
)

num_classes = len(label_encoder.classes_)

rnn_model = Sequential([
    Embedding(input_dim=VOCAB_SIZE, output_dim=EMBED_DIM, input_length=MAX_LEN),
    SimpleRNN(RNN_UNITS, return_sequences=True),
    Dropout(0.3),
    SimpleRNN(64),
    Dropout(0.3),
    Dense(64, activation="relu"),
    Dense(num_classes, activation="softmax"),
])

rnn_model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])
rnn_model.summary()

early_stop = EarlyStopping(monitor="val_accuracy", patience=3, restore_best_weights=True)

history = rnn_model.fit(
    X_train_seq, y_train,
    validation_data=(X_val_seq, y_val),
    epochs=15,
    batch_size=128,
    callbacks=[early_stop],
    verbose=2,
)

rnn_pred = np.argmax(rnn_model.predict(X_val_seq, verbose=0), axis=1)
rnn_accuracy = accuracy_score(y_val, rnn_pred)
print(f"SimpleRNN validation accuracy: {rnn_accuracy:.4f}")

rnn_model.save("models/rnn_model.keras")
joblib.dump(tokenizer, "models/rnn_tokenizer.joblib")

with open("models/rnn_accuracy.json", "w") as f:
    json.dump({"model": "SimpleRNN", "accuracy": rnn_accuracy}, f)

names = ["Multinomial NB", "SimpleRNN"]
scores = [nb_accuracy * 100, rnn_accuracy * 100]

plt.figure(figsize=(6, 5))
bars = plt.bar(names, scores, color=["#4C72B0", "#DD8452"])
plt.ylabel("Validation Accuracy (%)")
plt.title("ML vs DL Model Accuracy Comparison")
plt.ylim(0, 100)
plt.axhline(80, color="gray", linestyle="--", linewidth=1, label="80% target")

for bar, score in zip(bars, scores):
    plt.text(bar.get_x() + bar.get_width() / 2, score + 1.5,
              f"{score:.2f}%", ha="center", fontweight="bold")

plt.legend()
plt.tight_layout()
plt.savefig("outputs_accuracy_comparison.png", dpi=150)
plt.show()

# Commented out IPython magic to ensure Python compatibility.
# %%writefile preprocess.py
# """Shared text-cleaning function used by training and the app."""
# import re
# 
# def clean_text(text: str) -> str:
#     text = str(text).lower()
#     text = re.sub(r"http\S+|www\.\S+", " ", text)
#     text = re.sub(r"@\w+", " ", text)
#     text = re.sub(r"[^a-z\s]", " ", text)
#     text = re.sub(r"\s+", " ", text).strip()
#     return text
#

import json
import time
import joblib
import numpy as np
import streamlit as st
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.sequence import pad_sequences

from preprocess import clean_text

MODEL_DIR = "models"
RNN_MAX_LEN = 40

SENTIMENT_THEMES = {
    "Positive": {"color": "#059669", "bg": "#ECFDF5", "icon": "\U0001F60A"},
    "Negative": {"color": "#DC2626", "bg": "#FEF2F2", "icon": "\U0001F621"},
    "Neutral": {"color": "#2563EB", "bg": "#EFF6FF", "icon": "\u2696\uFE0F"},
    "Irrelevant": {"color": "#7C3AED", "bg": "#F5F3FF", "icon": "\U0001F3AF"},
}

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import json
# import time
# import joblib
# import numpy as np
# import streamlit as st
# from tensorflow.keras.models import load_model
# from tensorflow.keras.preprocessing.sequence import pad_sequences
# 
# from preprocess import clean_text
# 
# MODEL_DIR = "models"
# RNN_MAX_LEN = 40
# 
# SENTIMENT_THEMES = {
#     "Positive": {"color": "#059669", "bg": "#ECFDF5", "icon": "\U0001F60A"},
#     "Negative": {"color": "#DC2626", "bg": "#FEF2F2", "icon": "\U0001F621"},
#     "Neutral": {"color": "#2563EB", "bg": "#EFF6FF", "icon": "\u2696\uFE0F"},
#     "Irrelevant": {"color": "#7C3AED", "bg": "#F5F3FF", "icon": "\U0001F3AF"},
# }
# 
# CUSTOM_CSS = """
# <style>
# .app-header {
#     background: linear-gradient(135deg, #0F172A 0%, #1E293B 100%);
#     border-radius: 14px;
#     padding: 22px 28px;
#     color: #FFFFFF;
#     margin-bottom: 22px;
# }
# .app-title { font-size: 1.8rem; font-weight: 800; margin: 0; }
# .app-subtitle { color: #CBD5E1; font-size: 0.92rem; margin: 6px 0 0 0; }
# .result-card { border-radius: 14px; padding: 22px 26px; margin-top: 16px; }
# .sentiment-heading { font-size: 1.9rem; font-weight: 800; margin: 6px 0; }
# .confidence-val { font-size: 2rem; font-weight: 800; }
# .prob-row { margin-bottom: 12px; }
# .prob-labels { display: flex; justify-content: space-between; font-weight: 700; font-size: 0.9rem; margin-bottom: 4px; }
# .prob-track { width: 100%; height: 10px; background: #F1F5F9; border-radius: 9999px; overflow: hidden; }
# .prob-fill { height: 100%; border-radius: 9999px; }
# </style>
# """
# 
# 
# @st.cache_resource
# def load_naive_bayes():
#     model = joblib.load(f"{MODEL_DIR}/naive_bayes_model.joblib")
#     vectorizer = joblib.load(f"{MODEL_DIR}/tfidf_vectorizer.joblib")
#     with open(f"{MODEL_DIR}/nb_accuracy.json") as f:
#         accuracy = json.load(f)["accuracy"]
#     return model, vectorizer, accuracy
# 
# 
# @st.cache_resource
# def load_rnn():
#     model = load_model(f"{MODEL_DIR}/rnn_model.keras")
#     tokenizer = joblib.load(f"{MODEL_DIR}/rnn_tokenizer.joblib")
#     with open(f"{MODEL_DIR}/rnn_accuracy.json") as f:
#         accuracy = json.load(f)["accuracy"]
#     return model, tokenizer, accuracy
# 
# 
# @st.cache_resource
# def load_label_encoder():
#     return joblib.load(f"{MODEL_DIR}/label_encoder.joblib")
# 
# 
# def predict_naive_bayes(text, label_encoder):
#     start = time.time()
#     model, vectorizer, accuracy = load_naive_bayes()
#     features = vectorizer.transform([clean_text(text)])
#     probs = model.predict_proba(features)[0]
#     label = label_encoder.inverse_transform([np.argmax(probs)])[0]
#     return label, probs, accuracy, (time.time() - start) * 1000
# 
# 
# def predict_rnn(text, label_encoder):
#     start = time.time()
#     model, tokenizer, accuracy = load_rnn()
#     sequence = tokenizer.texts_to_sequences([clean_text(text)])
#     padded = pad_sequences(sequence, maxlen=RNN_MAX_LEN, padding="post", truncating="post")
#     probs = model.predict(padded, verbose=0)[0]
#     label = label_encoder.inverse_transform([np.argmax(probs)])[0]
#     return label, probs, accuracy, (time.time() - start) * 1000
# 
# 
# def render_result_card(label, confidence, accuracy, model_name, latency_ms):
#     theme = SENTIMENT_THEMES[label]
#     st.markdown(
#         f"""
#         <div class="result-card" style="background:{theme['bg']}; border:2px solid {theme['color']};">
#             <div style="display:flex; justify-content:space-between; align-items:flex-start; flex-wrap:wrap;">
#                 <h2 class="sentiment-heading" style="color:{theme['color']};">{theme['icon']} {label}</h2>
#                 <div style="text-align:right;">
#                     <div class="confidence-val" style="color:{theme['color']};">{confidence * 100:.1f}%</div>
#                     <div style="font-size:0.78rem; color:#64748B;">CONFIDENCE</div>
#                 </div>
#             </div>
#             <div style="margin-top:10px; font-size:0.85rem; color:#475569;">
#                 <b>{model_name}</b> \u00b7 validation accuracy {accuracy * 100:.2f}% \u00b7 {latency_ms:.1f} ms
#             </div>
#         </div>
#         """,
#         unsafe_allow_html=True,
#     )
# 
# 
# def render_probability_bars(classes, probs):
#     st.markdown("#### Probability breakdown")
#     for cls, prob in zip(classes, probs):
#         theme = SENTIMENT_THEMES[cls]
#         pct = prob * 100
#         st.markdown(
#             f"""
#             <div class="prob-row">
#                 <div class="prob-labels">
#                     <span>{theme['icon']} {cls}</span>
#                     <span style="color:{theme['color']};">{pct:.2f}%</span>
#                 </div>
#                 <div class="prob-track">
#                     <div class="prob-fill" style="width:{max(pct, 2):.2f}%; background:{theme['color']};"></div>
#                 </div>
#             </div>
#             """,
#             unsafe_allow_html=True,
#         )
# 
# 
# def main():
#     st.set_page_config(page_title="Twitter Sentiment Classifier", page_icon="\U0001F426", layout="centered")
#     st.markdown(CUSTOM_CSS, unsafe_allow_html=True)
# 
#     st.markdown(
#         """
#         <div class="app-header">
#             <h1 class="app-title">\U0001F426 Twitter Sentiment Classifier</h1>
#             <p class="app-subtitle">Classify a tweet as Positive, Negative, Neutral, or Irrelevant.</p>
#         </div>
#         """,
#         unsafe_allow_html=True,
#     )
# 
#     label_encoder = load_label_encoder()
# 
#     model_choice = st.selectbox("Choose a model:", ["Multinomial NB", "RNN"])
#     tweet = st.text_area("Tweet text:", placeholder="Type or paste a tweet here...", height=110)
# 
#     if st.button("Analyze Sentiment", type="primary"):
#         if not tweet.strip():
#             st.warning("Please enter some text first.")
#         else:
#             if model_choice == "Multinomial NB":
#                 label, probs, accuracy, latency = predict_naive_bayes(tweet, label_encoder)
#             else:
#                 label, probs, accuracy, latency = predict_rnn(tweet, label_encoder)
# 
#             render_result_card(label, np.max(probs), accuracy, model_choice, latency)
#             render_probability_bars(label_encoder.classes_, probs)
# 
# 
# if __name__ == "__main__":
#     main()
#

